archives:
  mgmt-letter-11-08:
    description: "In 2011, the National Archives' IG wrote management,
    baffled about the fact that its electronic records system, ERA, had
    no full text search, even after giving Lockheed Martin a 6-year,
    $430M contract."
    author: Eric Mill
    author_link: "https://twitter.com/konklone"
commerce:
  13-1077:
    description: "The US Patent Office's board of appeals wasted $5 million
    since 2009 by paying people to do nothing, as the nation's patent backlog
    continued rising. Senior management knew of this and allowed it to
    continue."
    author: Eric Mill
    author_link: "https://twitter.com/konklone"
